#!/bin/sh

echo "The program $0 is now running"
echo "The second parameter was $2"
echo "The first parameter was $1"
echo "The parameter list was $*"
echo "The user's home directory is $HOME"

~/linuxHW2/directory $1 $2 

echo "The script is now complete"

exit 0  
